
import streamlit as st
from prompt_templates import build_prompt
from llm import get_response

st.set_page_config(
    page_title="PromptCraft AI",
    page_icon="P",
    layout="wide"
)


def load_sample():
    st.session_state["task_input"] = (
        "Explain Artificial Intelligence to a beginner "
        "with a simple real-world example."
    )


if "generated_prompt" not in st.session_state:
    st.session_state["generated_prompt"] = ""

if "generated_response" not in st.session_state:
    st.session_state["generated_response"] = ""


st.markdown("""
<style>
.stApp {
    background: #0b1020;
    color: #f1f3ff;
}

[data-testid="stSidebar"] {
    background: #11182c;
}

.block-container {
    padding-top: 2rem;
    max-width: 1250px;
}

h1, h2, h3 {
    color: #e2e7ff;
}

.subtitle {
    color: #a8b2d1;
    font-size: 16px;
}

div.stButton > button {
    background: #7663ee;
    color: white;
    border: none;
    border-radius: 9px;
    min-height: 44px;
    font-weight: 600;
}

div.stButton > button:hover {
    background: #6250d2;
    color: white;
}

div[data-testid="stTextArea"] textarea {
    background: #141d33;
    color: white;
    border: 1px solid #303c5a;
    border-radius: 9px;
}

div[data-testid="stSelectbox"] {
    border-radius: 9px;
}
</style>
""", unsafe_allow_html=True)


with st.sidebar:
    st.title("PromptCraft AI")
    st.caption("PROMPT ENGINEERING STUDIO")
    st.divider()

    page = st.radio(
        "Navigation",
        ["Prompt Generator", "About Project"]
    )

    st.divider()
    st.caption("Powered by Hugging Face")
    st.caption(
        "Zero-shot | One-shot | Two-shot | Three-shot"
    )


if page == "Prompt Generator":

    st.title("Prompt Engineering Playground")

    st.markdown(
        '<p class="subtitle">Build a prompt, choose a technique, '
        'and explore the response generated by an LLM.</p>',
        unsafe_allow_html=True
    )

    st.divider()

    technique_names = {
        "Zero-shot": "zero-shot",
        "One-shot": "one-shot",
        "Two-shot": "two-shot",
        "Three-shot": "three-shot"
    }

    left, right = st.columns([1, 1], gap="large")

    with left:
        st.subheader("01  Configure Prompt")

        selected = st.selectbox(
            "Prompting Technique",
            list(technique_names.keys())
        )

        descriptions = {
            "Zero-shot": "Complete the task without examples.",
            "One-shot": "Use one example to guide the model.",
            "Two-shot": "Use two examples to guide the model.",
            "Three-shot": "Use three examples to guide the model."
        }

        st.caption(descriptions[selected])

        task = st.text_area(
            "Enter your task",
            placeholder="Example: Explain Artificial Intelligence",
            height=150,
            key="task_input"
        )

        st.button(
            "Load Sample Task",
            on_click=load_sample,
            use_container_width=True
        )

        generate = st.button(
            "Generate Prompt & Response",
            type="primary",
            use_container_width=True
        )

    if generate:
        if not task.strip():
            st.warning("Please enter your task first.")

        else:
            try:
                prompt = build_prompt(
                    technique_names[selected],
                    task
                )

                st.session_state["generated_prompt"] = prompt
                st.session_state["generated_response"] = ""

                with st.spinner("Generating AI response..."):
                    answer = get_response(prompt)

                st.session_state["generated_response"] = answer
                st.success("Prompt and response generated successfully.")

            except Exception as error:
                st.error(
                    "Unable to generate the AI response. "
                    "Check your Hugging Face token, model availability, "
                    "and internet connection."
                )
                st.caption(f"Technical details: {error}")

    with right:
        st.subheader("02  Generated Prompt")

        prompt = st.session_state["generated_prompt"]

        if prompt:
            st.code(prompt, language="text")

            st.download_button(
                "Download Prompt",
                data=prompt,
                file_name="generated_prompt.txt",
                mime="text/plain",
                use_container_width=True
            )

        else:
            st.info("Your generated prompt will appear here.")

    st.divider()

    st.subheader("03  LLM Response")

    answer = st.session_state["generated_response"]

    if answer:
        st.markdown(answer)
    else:
        st.info(
            "The AI-generated answer will appear here "
            "after you generate a prompt."
        )


else:
    st.title("About PromptCraft AI")

    st.write(
        "PromptCraft AI is a prompt engineering application "
        "that demonstrates how different numbers of examples "
        "can guide a large language model."
    )

    st.subheader("Technologies Used")

    st.markdown("""
    - Python for application logic
    - Streamlit for the web interface
    - Hugging Face InferenceClient for LLM requests
    - Qwen2.5-7B-Instruct as the configured model
    - Python dotenv for environment variable management
    """)

    st.subheader("Prompting Techniques")

    st.markdown("""
    - **Zero-shot:** No examples are provided.
    - **One-shot:** One example is provided.
    - **Two-shot:** Two examples are provided.
    - **Three-shot:** Three examples are provided.
    """)